[
  ./base.nix
  ./kitty.nix
  ./gpg.nix
  ./obs-studio/obs_studio.nix
  ./music.nix
  ./search.nix
  ./yt-dlp.nix
  ./mpv/mpv.nix
  ./neofetch/neofetch.nix
  ./firefox/firefox.nix
  ./zathura.nix
  ./ranger/ranger.nix
]
