[
  ./kitty.nix
  ./btop/btop.nix
  ./rofi.nix
  ./cava.nix
  ./obs_studio.nix
  ./notification.nix
  ./music.nix
  ./search.nix
  ./gpg.nix
  ./yt-dlp.nix
  ./mpv.nix
  ./imgview.nix
  ./hugo.nix
  ./dbeaver.nix
  ./lazygit.nix
  ./neofetch/neofetch.nix
  ./firefox/firefox.nix
]
